import type { TFunction } from "i18next";

const QWEN_DIAGNOSTIC_CODES = [
  "QWEN_RELATIVE_HOME",
  "QWEN_CONFIG_NOT_UTF8",
  "QWEN_MALFORMED_JSONC",
  "QWEN_ROOT_NOT_OBJECT",
  "QWEN_INVALID_PROPERTY_NAME",
  "QWEN_DUPLICATE_PROPERTY",
  "QWEN_UNSUPPORTED_VERSION",
  "QWEN_MODEL_PROVIDERS_NOT_OBJECT",
  "QWEN_PROVIDER_PROTOCOL_NOT_OBJECT",
  "QWEN_ENV_NOT_OBJECT",
  "QWEN_MODEL_NOT_OBJECT",
  "QWEN_SECURITY_NOT_OBJECT",
  "QWEN_SECURITY_AUTH_NOT_OBJECT",
  "QWEN_MANAGED_FIELD_NOT_OBJECT",
  "QWEN_PROVIDER_PROTOCOL_NOT_STRING",
  "QWEN_SELECTED_TYPE_NOT_STRING",
  "QWEN_ENFORCED_TYPE_NOT_STRING",
  "QWEN_USE_EXTERNAL_NOT_BOOLEAN",
  "QWEN_LEGACY_PROVIDER_SCHEMA",
  "QWEN_UNSUPPORTED_PROTOCOL",
  "QWEN_OPENAI_PROVIDER_NOT_ARRAY",
  "QWEN_OPENAI_MODEL_NOT_OBJECT",
  "QWEN_MODEL_ID_NOT_STRING",
  "QWEN_BASE_URL_NOT_STRING",
  "QWEN_ENV_CREDENTIAL_NOT_STRING",
  "QWEN_MISSING_MODEL_ID",
  "QWEN_MISSING_BASE_URL",
  "QWEN_INVALID_BASE_URL",
  "QWEN_INVALID_ENV_KEY",
  "QWEN_MISSING_FILE_CREDENTIAL",
  "QWEN_SPECIAL_ONLY_MODEL",
  "QWEN_SELECTED_ROUTE_NOT_FOUND",
  "QWEN_AMBIGUOUS_ROUTE",
  "QWEN_MISSING_SELECTION",
  "QWEN_UNSUPPORTED_AUTH",
  "QWEN_LEGACY_RUNTIME_CONFIG",
  "QWEN_EXTERNAL_OVERRIDE",
  "QWEN_TARGET_ENV_OVERRIDE",
  "QWEN_INCOMPATIBLE_CONNECTION",
  "QWEN_EXTERNAL_AUTH_POLICY",
  "QWEN_ENFORCED_AUTH_CONFLICT",
  "QWEN_EXTRA_AUTH_SETTINGS",
  "QWEN_GROUP_PROTOCOL_CONFLICT",
  "QWEN_GROUP_TYPE_CONFLICT",
  "QWEN_RENDER_VERIFY_FAILED",
  "QWEN_RESTART_REQUIRED",
  "QWEN_OAUTH_UNSUPPORTED",
] as const;

function fixedQwenCode(message: string): (typeof QWEN_DIAGNOSTIC_CODES)[number] | undefined {
  return QWEN_DIAGNOSTIC_CODES.find(
    (code) => message === code || message.endsWith(`: ${code}`) || message.startsWith(`${code}: `),
  );
}

export function diagnosticText(t: TFunction, message: string): string {
  const code = fixedQwenCode(message);
  return code ? t(`qwenDiagnostics.${code}`) : message;
}
